FROM  mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "TigerServer.sln"

COPY . ./
RUN dotnet build "TigerServer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TigerServer.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0 as final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TigerServer.dll"]
